<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html>
      <head>
        <title>XML Sitemap</title>
        <meta charset="UTF-8"/>
        <style>
          * { box-sizing: border-box; margin: 0; padding: 0; }
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f7f7f7; color: #333; font-size: 14px; }
          #header { background: #fff; border-bottom: 2px solid #e5e7eb; padding: 20px 32px; }
          #header h1 { font-size: 20px; font-weight: 700; color: #111827; margin-bottom: 4px; }
          #header p { font-size: 13px; color: #6b7280; }
          #header a { color: #2563eb; text-decoration: none; }
          #header a:hover { text-decoration: underline; }
          #content { max-width: 1100px; margin: 24px auto; padding: 0 24px 48px; }
          .info { display: inline-block; background: #fff; border: 1px solid #e5e7eb; border-radius: 6px; padding: 10px 16px; margin-bottom: 16px; font-size: 13px; color: #6b7280; }
          .info strong { color: #111827; }
          table { width: 100%; border-collapse: collapse; background: #fff; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.06); }
          thead tr { background: #f9fafb; }
          th { text-align: left; padding: 10px 16px; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.07em; color: #9ca3af; border-bottom: 1px solid #e5e7eb; }
          td { padding: 10px 16px; border-bottom: 1px solid #f3f4f6; font-size: 13px; vertical-align: middle; }
          tbody tr:last-child td { border-bottom: none; }
          tbody tr:hover td { background: #f9fafb; }
          td a { color: #2563eb; text-decoration: none; word-break: break-all; }
          td a:hover { text-decoration: underline; }
          .lastmod { color: #9ca3af; white-space: nowrap; font-size: 12px; }
          .freq { color: #9ca3af; font-size: 12px; }
          .pri { text-align: center; font-weight: 600; font-size: 12px; }
          .hi { color: #16a34a; }
          .md { color: #2563eb; }
          .lo { color: #d97706; }
          .vl { color: #9ca3af; }
        </style>
      </head>
      <body>
        <div id="header">
          <h1>XML Sitemap</h1>
          <p>Generated by <a href="https://www.andressaumet.com">andressaumet.com</a> — for consumption by search engines.</p>
        </div>
        <div id="content">

          <!-- Sitemap Index -->
          <xsl:if test="sitemap:sitemapindex">
            <p class="info">
              This sitemap index contains
              <strong><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/> sitemaps</strong>.
            </p>
            <table>
              <thead>
                <tr>
                  <th>Sitemap</th>
                  <th>Last Modified</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                  <tr>
                    <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
                    <td class="lastmod"><xsl:value-of select="sitemap:lastmod"/></td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>

          <!-- URL Set -->
          <xsl:if test="sitemap:urlset">
            <p class="info">
              This sitemap contains
              <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs</strong>.
            </p>
            <table>
              <thead>
                <tr>
                  <th>URL</th>
                  <th>Last Modified</th>
                  <th>Change Freq</th>
                  <th style="text-align:center">Priority</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:urlset/sitemap:url">
                  <tr>
                    <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
                    <td class="lastmod"><xsl:value-of select="sitemap:lastmod"/></td>
                    <td class="freq"><xsl:value-of select="sitemap:changefreq"/></td>
                    <td>
                      <xsl:attribute name="class">
                        <xsl:choose>
                          <xsl:when test="number(sitemap:priority) &gt;= 0.8">pri hi</xsl:when>
                          <xsl:when test="number(sitemap:priority) &gt;= 0.6">pri md</xsl:when>
                          <xsl:when test="number(sitemap:priority) &gt;= 0.4">pri lo</xsl:when>
                          <xsl:otherwise>pri vl</xsl:otherwise>
                        </xsl:choose>
                      </xsl:attribute>
                      <xsl:value-of select="sitemap:priority"/>
                    </td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>

        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
